var veg1 = "Potato";
var veg2 = "Tomato";
console.log(veg1 === veg2);
console.log(veg1 !== veg2);
var myName = "Hamid Naeem";
var lowerCaseString = myName.toLowerCase();
console.log(lowerCaseString === "Hamid Naeem");
console.log(lowerCaseString !== "Hamid Naeem");
var num1 = 5;
var num2 = 10;
console.log(num1 === num2);
console.log(num1 !== num2);
console.log(num1 > num2);
console.log(num1 < num2);
console.log(num1 >= num2);
console.log(num1 <= num2);
var g = true;
var h = false;
console.log(g && h);
console.log(g || h);
var stationary = ["Ink pen", "Pencil", "Eraser", "Sharpner", "Scale"];
console.log(stationary.push("Ink pen"));
console.log(stationary.push("Ink Pen"));
